### ISSUE TITLE
Holotoolkit is only at Unity2017.1.0f1 but MRDesignLabs is at 2017.2b

### ISSUE THREAD

**Issue by ei2kpi** [Microsoft/MRDesignLabs_Unity_Tools#13]
For example, in [InteractionManagerInspector.cs](https://github.com/Microsoft/MRDesignLabs_Unity_Tools/blob/master/HUX/Editor/InteractionManagerInspector.cs) the XR namespace is used instead of VR

**Comment by paseb** [comment]
Yeah, that should not have been checked in or committed to the master but should be in branch.

thanks,
-pat

**Comment by paseb** [comment]
Updated and checked in.
