### ISSUE TITLE
Axis Scaling

### ISSUE THREAD

**Issue by Zod-** [Microsoft/MRDesignLabs_Unity_Tools#19]
I'm wondering, is the scaling in x,y and z axis implemented or is it missing from the BoundingBoxShell? I haven't found anything referencing it directly so I started implementing it on my own but there're quite a lot of classes it has to be added.

**Comment by Railboy** [comment]
So far we've only implemented uniform scaling, but we've left the door open for individual axis later down the line.

**Comment by Zod-** [comment]
Alright, thanks. Took me a while but I managed to get it working decently https://my.mixtape.moe/thbryn.mp4. Mostly had issues with applying the scaling to the transformHelper as it seemed like the rotation always interfered.
