### ISSUE TITLE
3 Errors Returned On Import

### ISSUE THREAD

**Issue by reillydonovan** [Microsoft/MRDesignLabs_Unity_Tools#2]
Hello, when I import this into my Unity asset folder I am returned the following errors:

Removing Assets/MRDesignLabs_Unity_Tools/HUX/Resources/Models/Cursor/Cursor_move/CursorRing.fbm/templates because the asset does not exist
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEditor.DockArea:OnGUI()

Unsupported DDS file.
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEditor.DockArea:OnGUI()

Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/UAudioManager.cs(463,10): error CS0616: `ContextMenu': is not an attribute class

any suggestions?  thanks!

**Comment by paseb** [comment]
Sorry for the late reply on this.  The first 2 errors you can ignore.  The first one is a bad meta file on an auto-generated directory from an fbx import.  The second one is a dds file that is coupled with the cursor fbx. 

However the 3rd one could be based on the version of Unity you're using or not have the build settings targeting UWP.  What are your settings for building and which version of Unity are you using?

thanks,
-pat

**Comment by HattMarris1** [comment]
I also have this issue, I'm using unity 5.6, and I'm targeting the windows store (I can paste a screen shot of the build settings if that's easier)

Thanks,

**Comment by reillydonovan** [comment]
I'm using 5.6.2f1 and the build setttings are set to UWP with hololens as a target.  I can get it to work if I download HUX from the github source repo rather than from the git submodule, however I am still returned the top two errors but I can still build.

**Comment by paseb** [comment]
As I mentioned the top 2 errors are just import errors and not critical ones.  I'll remove the offenders anyway but what to make sure that use it as a submodule should but the correct approach.  So @reillydonovan you have a git repo that you were creating the submodule in and getting the 3rd error above from HTK?

To be clear on the repo steps I'm going to test with the following (as all of them should work):
- Option 1: Create a new project and clone MRDesignLab_Unity_Tools into Assets with current HTK in project.
- Option 2: Create fork of HoloToolkit and add MRDesignLabs_Unity_Tools as a submodule
- Option 3: Create a stand alone repo and project and add MRDesignLabs_Unity_Tools as a submodule with HTK

Do these are seem viable and which structure are you using?

thanks,
-pat

**Comment by reillydonovan** [comment]
Option 1 above worked for me.
I didn't try Option 2.
Option 3 is the option that I did try without success, but I can try again.

**Comment by paseb** [comment]
Awesome!  All 3 should be resolved.   I removed the offending dds and meta file to nowhere and updated the context menu in HUX to be in the cursors namespace as well as named it appropriately.  It's now ContextCursorMenu since that's really what it was intended for.

**Comment by reillydonovan** [comment]
That worked, thanks, I can now use the submodule.  The DDS still reports an error but doesn't prevent me from building the solution.

**Comment by paseb** [comment]
D'oh! I'll delete the other dds then as well as they're not being used currently.

Thanks,
-pat
