### ISSUE TITLE
Using Fluent Design controls outside HoloToolkit

### ISSUE THREAD

**Issue by abhilashca** [Microsoft/MRDesignLabs_Unity_Tools#29]
Hello,

I am trying to use Fluent Design controls in one of my Unity project. I added _MRDesignLabs_Unity_Tools_ in a sample Unity project and got compile errors which are dependent on HoloToolkit.

Is it possible for to use the Controls like Buttons, Dialogs, etc. outside HoloToolkit?

Any help will be appreciated.
Thank you.

**Comment by paseb** [comment]
You should be able to grab an earlier version of the tools that do not take a dependency on HoloToolkit.  I think the 5.6 MRTP version has the least dependencies.  We will be releasing a stand-alone version of HUX in the near future for rapid prototyping.
