### ISSUE TITLE
CompoundButton[X]Inspector(s) should allow for EditMultipleObjects

### ISSUE THREAD

**Issue by ei2kpi** [Microsoft/MRDesignLabs_Unity_Tools#9]
When you have a lot of buttons, it becomes a pain to have to assign the buttons profiles individually.
The CompounButton[x]Inspector classes should add the [CanEditMultipleObjects] attribute and properly support it.

Note: Might need to look at [this ](http://answers.unity3d.com/questions/637744/caneditmultipleobjects-doesnt-actually-work-for-an.html) for help on how to properly support multiple object assignments.

**Comment by Railboy** [comment]
Good suggestion, thank you.
